export const songs = [


    {
	id:1,
        title: "Amazing Grace",
        artist: "John Newton",
        key: "G",
        category: "Hymn",
        language: "English",
        file: "songs/amazing-grace.html"
    },

    {
	id:2,
        title: "I Love This Family",
        artist: "JFCM",
        key: "A",
        category: "Praise",
        language: "English",
        file: "songs/ilovethisfamily.html"
	
	    },

    {
        id:3,
	title: "My Life is in You Lord",
        artist: "Joseph Garlington",
        key: "G",
        category: "Praise",
        language: "English",
        file: "songs/mylifeisinyoulord.html"
    },

    {
	id:4,
        title: "Holy, Holy, Holy",
        artist: "Reginald Heber",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/holy-holy-holy.html"
    },
{
id:5,
        title: "Blessed be the Name of the Lord",
        artist: "Don Moen",
        key: "G",
        category: "Praise",
        language: "English",
        file: "songs/blessedbethename.html"
    },
{
id:6,
        title: "Beautiful Saviour",
        artist: "Planet Shaker",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/beautifulsaviour.html"
    },
{
	id:7,
        title: "How Great is Our God",
        artist: "Chris Tomlin",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/howgreatisourgod.html"
    },
{
id:8,        
title: "Freely Forgiven",
        artist: "New Church Creation",
        key: "G",
        category: "Praise",
        language: "English",
        file: "songs/freelyforgiven.html"
    },
{
id:9,        
title: "Tinapay ng Buhay",
        artist: "Bukas Palad Music Ministry",
        key: "D",
        category: "Worship",
        language: "Tagalog",
        file: "songs/tinapayngbuhay.html"
    },
{
id:10,        
title: "Give Thanks",
        artist: "Don Moen",
        key: "D",
        category: "Worship",
        language: "English",
        file: "songs/givethanks.html"
    },
{
id:11,        
title: "Worthy is the Lamb",
        artist: "Hillsong Worship",
        key: "D",
        category: "Worship",
        language: "English",
        file: "songs/worthyisthelamb.html"
    },
{
id:12,        
title: "It's Your Blood",
        artist: "Rodrigo Silva",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/itsyourblood.html"
    },
{
id:13,        
title: "For the Lord is my Tower",
        artist: "Misc Praise Songs",
        key: "G",
        category: "Praise",
        language: "English",
        file: "songs/forthelordismytower.html"
    },
{
id:14,        
title: "Sama Samang Nagpupuri",
        artist: "Musikatha",
        key: "A",
        category: "Praise",
        language: "Tagalog",
        file: "songs/samasamangnagpupuri.html"
    },
{
id:15,        
title: "Awiting May Galak",
        artist: "Faith Music Manila",
        key: "E",
        category: "Praise",
        language: "Tagalog",
        file: "songs/awitingmaygalak.html"
    },
{
id:16,        
title: "Sumigaw sa Galak",
        artist: "Musikatha",
        key: "E",
        category: "Praise",
        language: "Tagalog",
        file: "songs/sumigawsagalak.html"
    },
{id:17,        
title: "Sukdulang Biyaya",
        artist: "Musikatha",
        key: "D",
        category: "Worship",
        language: "Tagalog",
        file: "songs/sukdulangbiyaya.html"
    },
{id:18,        
title: "Napakabuti Mo",
        artist: "Rommel Guevara",
        key: "G",
        category: "Worship",
        language: "Tagalog",
        file: "songs/napakabutimo.html"
    },
{id:19,        
title: "O Kay Saya at Kay Ganda",
        artist: "Misc Praise Songs",
        key: "A",
        category: "Praise",
        language: "Tagalog",
        file: "songs/okaysayaatkayganda.html"
    },
{id:20,        
title: "Magpakailanman",
        artist: "Passion Generation Worship Band",
        key: "D",
        category: "Praise",
        language: "Tagalog",
        file: "songs/magpakailanman.html"
    },
	{id:21,        
title: "I Love to be in Your Presence",
        artist: "Don Moen",
        key: "E",
        category: "Praise",
        language: "English",
        file: "songs/ilovetobeinyourpresence.html"
    },
	{id:22,        
title: "How Good It Is",
        artist: "EDGAR GUNGOR- DANNY CHAMBERS",
        key: "G",
        category: "Praise",
        language: "English",
        file: "songs/howgooditis.html"
    },
	{id:23,        
title: "Forever",
        artist: "Chris Tomlin",
        key: "D",
        category: "Praise",
        language: "English",
        file: "songs/forever.html"
    },
	{id:24,        
title: "Always",
        artist: "Marty Nystrom",
        key: "D",
        category: "Worship",
        language: "English",
        file: "songs/always.html"
    },
	{id:25,        
title: "You Are God Alone",
        artist: "BILLY & CINDY FOOTE",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/youaregodalone.html"
    },
	{id:26,        
title: "Holy Forever",
        artist: "Chris Tomlin",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/holyforever.html"
    },
	{id:27,        
title: "Kamusta Ka Na",
        artist: "Misc Praise Songs",
        key: "D",
        category: "Praise",
        language: "Tagalog",
        file: "songs/kamustakana.html"
    },
		{id:28,        
title: "Sa Biyaya",
        artist: "Spring Worship",
        key: "C",
        category: "Praise",
        language: "Tagalog",
        file: "songs/sabiyaya.html"
    },
		{id:29,        
title: "Ikaw Lamang",
        artist: "Rommel Guevara",
        key: "G",
        category: "Worship",
        language: "Tagalog",
        file: "songs/ikawlamang.html"
    },
		{id:30,        
title: "Alay Sa Pagsamba",
        artist: "Rommel Guevara",
        key: "A",
        category: "Worship",
        language: "Tagalog",
        file: "songs/alaysapagsamba.html"
    },
	{id:31,        
title: "Mahal na Mahal Kita Panginoon",
        artist: "Rommel Guevara",
        key: "G",
        category: "Praise",
        language: "Tagalog",
        file: "songs/mahalnamahalkita.html"
    },
	{id:32,        
title: "Tayo Na Sama Sama",
        artist: "Mega Harvest",
        key: "C",
        category: "Praise",
        language: "Tagalog",
        file: "songs/tayonasamasama.html"
	},
	{id:33,        
title: "Sabik sa Presensya",
        artist: "Faith Music Manila",
        key: "A",
        category: "Praise",
        language: "Tagalog",
        file: "songs/sabiksapresensya.html"
	},
	{id:34,        
title: "Kahanga Hanga",
        artist: "Faith Music Manila",
        key: "A",
        category: "Praise",
        language: "Tagalog",
        file: "songs/kahangahanga.html"
	},
	{id:35,        
title: "Awit Ng Pasasalamat",
        artist: "Shekinah Glory",
        key: "B",
        category: "Praise",
        language: "Tagalog",
        file: "songs/awitngpasasalamat.html"
	},
	{id:36,        
title: "Ako'y Magtitiwala Sayo",
        artist: "Musikatha",
        key: "D",
        category: "Worship",
        language: "Tagalog",
        file: "songs/akoymagtitiwalasayo.html"
	},
	{id:37,        
title: "Mga Pangako Mo",
        artist: "Faith Music Manila",
        key: "G",
        category: "Worship",
        language: "Tagalog",
        file: "songs/mgapangakomo.html"
	},
	{id:38,        
title: "Ako'y Nananabik",
        artist: "Spring Worship",
        key: "E",
        category: "Praise",
        language: "Tagalog",
        file: "songs/akoynananabik.html"
	},
	{id:39,        
title: "Itatanghal",
        artist: "Spring Worship",
        key: "G",
        category: "Worship",
        language: "Tagalog",
        file: "songs/itatanghal.html"
	},
	{id:40,        
title: "Wala Kang Katulad",
        artist: "Faith Music Manila",
        key: "D",
        category: "Worship",
        language: "Tagalog",
        file: "songs/walakangkatulad.html"
	},
	{id:41,        
title: "I Sing Praises To Your Name",
        artist: "Terry Macalmon",
        key: "G",
        category: "Worship",
        language: "English",
        file: "songs/isingpraises.html"
	},
	{id:42,        
title: "Ngalan Mo'y Itataas",
        artist: "Terry Macalmon",
        key: "B",
        category: "Worship",
        language: "Tagalog",
        file: "songs/ngalanmoyitataas.html"
	},
	{id:43,        
title: "Papuri Kay Yahweh",
        artist: "Hope Filipino Worship",
        key: "E",
        category: "Praise",
        language: "Tagalog",
        file: "songs/papurikayyahweh.html"
	},
	{id:44,        
title: "Diyos Ka Sa Amin",
        artist: "Hope Filipino Worship",
        key: "E",
        category: "Worship",
        language: "Tagalog",
        file: "songs/diyoskasaamin.html"
	},
	{id:45,        
title: "Happy Day",
        artist: "Tim Hughes",
        key: "C",
        category: "Praise",
        language: "English",
        file: "songs/happyday.html"
	}
	];
songs.sort((a, b) =>
    a.title.localeCompare(b.title)
);
